# Generated by Django 4.2.30 on 2026-05-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_session_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='dummy_field',
        ),
    ]
